# Generated by Django 2.1.7 on 2019-02-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='q2',
        ),
    ]
