# Generated by Django 2.1.7 on 2019-02-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_q1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='q1',
        ),
    ]
