# Generated by Django 2.1.7 on 2019-02-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_q1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='q2',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
