# Generated by Django 2.1.7 on 2019-02-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_submit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='submit_count',
        ),
    ]
