# Generated by Django 2.1.7 on 2019-02-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_submit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
