# Generated by Django 2.1.7 on 2019-03-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190307_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='q1',
            field=models.CharField(default='help text for q1', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='q2',
            field=models.CharField(default='help text for q2', max_length=200),
        ),
    ]
