# Generated by Django 2.1.7 on 2019-03-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190307_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='q2',
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-1-H',
            field=models.TextField(default='গান খুবই অসাধারণ একটা জিনিস, এমন কিছু গান বল যেগুলো শুনে হয়তো আমাদের কথা মনে পড়বে বা এমনিই\n         শুনে মজা পাবো'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-1-Q',
            field=models.CharField(default='একটা ভালো দেখে গানের লিস্ট দে', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-10-H',
            field=models.TextField(default=' ফার্স্ট ইয়ারের প্রথম কিছুদিন ছাড়া আমাকে এই ডাকনামে ডাকে নি কেউ আর। আর আমার আর কিছু জানাও নেই।  '),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-10-Q',
            field=models.CharField(default='"বাবা" ছাড়া আমার আর যদি কোন ডাকনাম থেকে থাকে... ', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-11-H',
            field=models.TextField(default=' এতক্ষনে নিশ্চই বহু কথা মনে পড়ে গেছে এই তিনবছরের। যেগুলো বলা হয়নি; বা যেগুলো এই তিনবছরে করা হয় নি, সবকিছু.... '),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-11-Q',
            field=models.CharField(default='২০১৬ থেকে ২০১৯ .... কি কি ঘটল.... কি কি বদলাল....', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-2-H',
            field=models.TextField(default=' সিনেমা দেখতে সবসময়েই ঘ্যাম লাগে। আমার প্রিয় কিছু সিনেমা হল:\n                ১. kung fu  panda \n                ২. barfi \n                ৩. batman - dark  knight \n                ৪. inception \n                ৫. বিসর্জন \n            এর মধ্যে কোনোটা  না দেখে থাকলে শিগগিরি দেখে না। তোর ভালো লাগা কিছু সিনেমা এখানে লিখে ফেল  '),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-2-Q',
            field=models.CharField(default='তোর প্রিয়  কিছু সিনেমা', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-3-H',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-3-Q',
            field=models.CharField(default='আমার মধ্যে যে জিনিসটা তোর ভালো লাগে...', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-4-H',
            field=models.TextField(default=' এই তিন বছরে আমি অন্তত প্রচুর আজেবাজে, উল্টোপাল্টা, দারুন অথবা, ভয়ানক কাজ করে বেড়িয়েছি। \n        তোর সাথে যদি তেমন কোন ঘটনা ঘটে থাকে তো সেটা বল।   '),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-4-Q',
            field=models.CharField(default='আমরা যেসব ভালো স্মরণীয় মুহূর্ত কাটিয়েছি...', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-5-H',
            field=models.TextField(default='সবারই জীবনে কিছু শখ বা স্বপ্ন থাকে, যেমন ধর আমার স্বপ্ন ছিল এই ওয়েবসাইটটা  বানাবো....  🤣🤣 ।  \n        নিজের সম্পর্কে বল'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-5-Q',
            field=models.CharField(default='তোর যদি কোন স্বপ্ন থাকে সেটা কি?', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-6-H',
            field=models.TextField(default=' তোর যদি আমার কোন স্বভাব বা আচরণ যদি পরিবর্তন করা উচিত বলে মনে হয়.... কিছু পরামর্শ দে।  '),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-6-Q',
            field=models.CharField(default='আমার সম্পর্কে যে জিনিসটা তুই পছন্দ করিস না', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-7-H',
            field=models.TextField(default=' 😂😂😂 বলে থাকতেই পারিস, ঘটনা পুরো বলে ফেল   😂\n         (এই উত্তর গুলো আমি জুন মাসের আগে দেখব না আরেকবার মনে করিয়ে দিই)  '),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-7-Q',
            field=models.CharField(default='আমাকে বলা একটা মিথ্যে কথা....', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-8-H',
            field=models.TextField(default=' আমিও একটু জানি, এই তিনবছর কি কি গুজব চললো... '),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-8-Q',
            field=models.CharField(default='আমাকে নিয়ে শোনা কোন গুজব', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-9-H',
            field=models.TextField(default=' আমাকে প্রথম দেখে কাকু কাকু মনে হয় বহুবার শুনেছি...  😅😅😅\n        যা কিছু মনে হয়েছিল খুলে বলে ফেল, আমার জানতে ভালোই লাগবে। '),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question-9-Q',
            field=models.CharField(default='ফার্স্ট ইম্প্রেশন ভার্সেস লাস্ট ইম্প্রেশন ', max_length=400),
        ),
    ]
