# Generated by Django 2.1.7 on 2019-02-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='title',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
