# Generated by Django 2.1.7 on 2019-02-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_form', '0003_responsemodel_submit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemodel',
            name='submit_count',
        ),
    ]
