# Generated by Django 2.1.7 on 2019-03-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_form', '0006_remove_responsemodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemodel',
            name='ans1',
        ),
        migrations.RemoveField(
            model_name='responsemodel',
            name='ans2',
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-1',
            field=models.TextField(blank=True, verbose_name='একটা ভালো দেখে গানের লিস্ট দে'),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-10',
            field=models.TextField(blank=True, verbose_name='"বাবা" ছাড়া আমার আর যদি কোন ডাকনাম থেকে থাকে... '),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-11',
            field=models.TextField(blank=True, verbose_name='২০১৬ থেকে ২০১৯ .... কি কি ঘটল.... কি কি বদলাল....'),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-2',
            field=models.TextField(blank=True, verbose_name='তোর প্রিয়  কিছু সিনেমা'),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-3',
            field=models.TextField(blank=True, verbose_name='আমার মধ্যে যে জিনিসটা তোর ভালো লাগে...'),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-4',
            field=models.TextField(blank=True, verbose_name='আমরা যেসব ভালো স্মরণীয় মুহূর্ত কাটিয়েছি...'),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-5',
            field=models.TextField(blank=True, verbose_name='তোর যদি কোন স্বপ্ন থাকে সেটা কি?'),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-6',
            field=models.TextField(blank=True, verbose_name='আমার সম্পর্কে যে জিনিসটা তুই পছন্দ করিস না'),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-7',
            field=models.TextField(blank=True, verbose_name='আমাকে বলা একটা মিথ্যে কথা....'),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-8',
            field=models.TextField(blank=True, verbose_name='আমাকে নিয়ে শোনা কোন গুজব'),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='question-9',
            field=models.TextField(blank=True, verbose_name='ফার্স্ট ইম্প্রেশন ভার্সেস লাস্ট ইম্প্রেশন '),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='rpublic',
            field=models.BooleanField(default=False),
        ),
    ]
