# Generated by Django 2.1.7 on 2019-03-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_form', '0007_auto_20190308_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='final_res',
            field=models.TextField(blank=True),
        ),
    ]
